<div id="usecases">
  <header>
    <h1>Use Cases</h1>
  </header>

  <section>
    <div class="usecases-block">
      <img src="{{ asset('img/e-commerce.svg') }}" alt="User flow" width="200" height="200">

      <h3>E-commerce</h3>
      <p>Managing an ecommerce store that scales to various countries and regions, requires communicating prices in languages users are used to.</p>
    </div>

    <div class="usecases-block">
      <img src="{{ asset('img/sales-receipt.svg') }}" alt="User flow" width="200" height="200">

      <h3>Receipts and Invoices</h3>
      <p>Autogenerated invoices should feel more natural to paper invoices. People grew up reading monetary values, making it first hand in an invoice should be a great desire.</p>
    </div>

    <div class="usecases-block">
      <img src="{{ asset('img/stranded-traveler.svg') }}" alt="User flow" width="200" height="200">

      <h3>Tourism</h3>
      <p>First point of contact for local tourists in new locations are usually the market places. Displaying monetary values in their natural language fosters easy trading.</p>
    </div>
  </section>
</div>